version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: loganrun2020/refactor-udagram:reverseproxy
  backend_user:
    build:
      context: ../../backend-user-api
    image: loganrun2020/refactor-udagram:udagram-user
  backend_feed:
    build:
      context: ../../backend-feed-api
    image: loganrun2020/refactor-udagram:udagram-feed
  frontend:
    build:
      context: ../../frontend
    image: loganrun2020/refactor-udagram:udagram-frontend