version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: loganrun2020/refactor-udagram:reverseproxy
  udagram-user:
    build:
      context: ../../udagram-users
    image: loganrun2020/refactor-udagram:udagram-user
  udagram-feed:
    build:
      context: ../../udagram-feed
    image: loganrun2020/refactor-udagram:udagram-feed
  frontend:
    build:
      context: ../../frontend
    image: loganrun2020/refactor-udagram:udagram-frontend