version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: loganrun2020/reverseproxy
  udagram-user:
    build:
      context: ../../udagram-users
    image: loganrun2020/udagram-user
  udagram-feed:
    build:
      context: ../../udagram-feed
    image: loganrun2020/udagram-feed
  frontend:
    build:
      context: ../../udagram-frontend
    image: loganrun2020/udagram-frontend