apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-front
  name: udagram-front
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-front
  template:
    metadata:
      labels:
        service: udagram-front
        api: external
    spec:
      containers:
      - image: loganrun2020/udagram-front:1.1
        name: udagram-front
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
      restartPolicy: Always